### ISSUE TITLE
Ignores fonts

### ISSUE THREAD

**Issue by Ikrom27** [colintheshots/MarkdownTwain#4]
I can’t install my fonts, neither through themes nor through text styles, judging by the code, it generally ignores fonts from the text style

**Comment by colintheshots** [comment]
This is possible. However, the usual Compose methods won't work for now. I created this library using Android Views in order to very quickly build it from the Markwon library. This means the underlying text field is actually an EditText View.

As a workaround to set the text fonts and style (until the code is updated to be purely Compose-based), one can get a reference to the underlying EditText View and set the font using the Views system. Put the font in the res/font resources folder. In this example, res/font/test_font.ttf.

```
val text = rememberSaveable { mutableStateOf("") }
val view = remember { mutableStateOf<EditText?>(null) }
MarkdownEditor(
    value = text.value,
    onValueChange = { text.value = it },
    setView = { view.value = it }
)
LaunchedEffect(Unit) {
    val tf: Typeface = resources.getFont(R.font.test_font)
    view.value?.setTypeface(tf)
}
```
